### PR TITLE
[WIP] adding initial modules

### PR DESCRIPTION
**Pull request by choldgraf**
This is the first proposed structure for `sphinx-gallery-extra`. It's still WIP, but I wanted to post the structure sooner than later so that people could comment on how it's set up.

I'd ideally like this repository to be much more "yes, and" than the `sphinx-gallery` base repo. It should be a place where people are encouraged more to experiment and push the boundaries as opposed to being conservative about making sure all possible workflows, versions, etc are supported.

Right now it's organized as a "traditional" python module that is installable, with its own documentation, etc. What do folks think about this?

### CODE REVIEW

**Comment by t-makaro** [comment]
I agree with the idea of a traditional python module. I do think that the submodules should not be imported by default. (which I think you have done).

**Comment by choldgraf** [comment]
could you explain more what you mean by "not imported by default"? Just not sure how I should change the code to avoid this :-)

**Comment by t-makaro** [comment]
I just mean that you should have to import the subpackages explicitly. ```import sphinx_gallery_extra``` would not import ```sphinx_gallery_extra.scrappers``` which would require it's own import. Scipy does this. I believe that's just the behaviour of having an empty ```__init__.py```.

**Comment by choldgraf** [comment]
ahh gotcha - yep that's a good idea

**Comment by jni** [comment]
Hey @choldgraf still up for helping us get this into skimage? @leGIT-bot is a student working with me and he did the cool registration animations that first got me excited about this. He's got some time to get this working now so we would appreciate some help! This PR has some funkiness going on (see e.g. [here](https://github.com/sphinx-gallery/sphinx-gallery-extra/pull/1/files#diff-e5672a08cb735ed8d7867e1b4f809bf7R5)), so it would be great if he could get some guidance from you to get a PR into skimage to include this scraper and add mpl gifs to the docs!

**Comment by choldgraf** [comment]
hey - I can probably help a bit, though this PR is kinda stale so I probably don't remember it as well now. Anything that should be changed in this PR?

**Comment by jni** [comment]
Haha yes — @jakirkham was in the room with me and @leGIT-bot when we were discussing this and I was like, man, this PR's been sitting ignored for 3 months, and he was like, "Only 3 months? That's not so bad!" 🤦‍♂️ 

I don't know about the PR but the main issue is that I don't understand the sphinx/sphinx-gallery extension system. My basic idea of what needs to happen is:

- we put `image-scraper.py` somewhere in the scikit-image repo... [`doc/ext`](https://github.com/scikit-image/scikit-image/tree/master/doc/ext), perhaps?
- we somehow tell sphinx about the extension... how?
- now magically any examples where we use matplotlib to write out an animation gif will have the gif embedded?

Is that right? Can you fill in the details?

**Comment by choldgraf** [comment]
So I originally wrote the image scraper just as an exercise to understand the sphinx gallery scraper plugin system better anyway, and I updated those docs in the process. That PR still isn't merged but I bet if you combined the scraper code sample we've got along with those instructions, it should be ~ straightforward to figure out:

Here are the instructions, wanna give it a shot?

https://github.com/sphinx-gallery/sphinx-gallery/pull/417/files#diff-16e3dbccf13c8c447eff98d226c5d89b

**Comment by jni** [comment]
@leGIT-bot I think the scrapers configuration needs to be in the dictionary defining sphinx-gallery config in `doc/source/conf.py`. Can you get that WIP PR started so we can comment directly on the code?

**Comment by choldgraf** [comment]
just FYI the updated custom scraper documentation is now merged and here:

https://sphinx-gallery.github.io/advanced.html#writing-a-custom-image-scraper

**Comment by choldgraf** [comment]
I'm doing a bit of PR housekeeping, and closing this one as it is _very_ stale :-) anybody else should feel free to pick it up!

**Pull request closed without merging**
